### ISSUE TITLE
SettingForm中name字段长度与Admin.name不对应

### ISSUE THREAD

**Issue by Exmlyshy** [greyli/bluelog#12]
在models中设置Admin.name字段为db.String(30)，
[https://github.com/greyli/bluelog/blob/c74f258c7fe6af6cfc065ec311e7732141373c33/bluelog/models.py#L22](https://github.com/greyli/bluelog/blob/c74f258c7fe6af6cfc065ec311e7732141373c33/bluelog/models.py#L22)
但是在SettingForm中name字段设置为Length(1,70)，
[https://github.com/greyli/bluelog/blob/c74f258c7fe6af6cfc065ec311e7732141373c33/bluelog/forms.py#L25](https://github.com/greyli/bluelog/blob/c74f258c7fe6af6cfc065ec311e7732141373c33/bluelog/forms.py#L25)
，这两者应该是对应关系，测试时却发现可以超出指定长度，这应该是因为sqllite对应字段为TEXT。

**Comment by greyli** [comment]
谢谢，已在 https://github.com/greyli/bluelog/commit/4de60fa41b7e7a8b67d9064e2030661fdb4f827b 修复。
