### ISSUE TITLE
My explorer can not show it normally

### ISSUE THREAD

**Issue by scpcheers** [greyli/bluelog#13]
I use firefox explorer, when I run the flask project, the firefox only show font and links, the CSS can not show normally. Then, I test it in '双核浏览器'(chrome core) and IE explorer, they also can not show normally.

**Comment by greyli** [comment]
Please try to clear your browser cache. If it doesn't work, go check the network tab in the developer tools of your browser.

**Comment by scpcheers** [comment]
I'm clear them at all, but it's useless. Thank you for your suggestion. May be I should edit start over in myself.

**Comment by greyli** [comment]
Provide a screenshot of the network tab may be helpful.

**Comment by adlerliu** [comment]
中文识别问题，这个怎么生效。我改了语言不生效。还有登录的为什么不放到上面。

**Comment by scpcheers** [comment]
I find the solution that '出现错误的原因应该是网页文档类型的不一致导致的（）。我们只要把网页的头部“<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">”删除，网页的显示就正常了 '. Then my brower(firefox) can show it normally. Thanks.
