### ISSUE TITLE
中文显示

### ISSUE THREAD

**Issue by adlerliu** [greyli/bluelog#14]
我设置了中文显示问题，怎么不生效，还有登录接口调节上面需要怎么改进

**Comment by greyli** [comment]
> 我设置了中文显示问题，怎么不生效

不好意思，我不理解你的问题是什么。请详细描述。

> 登录接口调节上面需要怎么改进

如果你是说登录链接的位置，你可以自己随意改动，只要移动那部分代码即可。

**Comment by adlerliu** [comment]
<html lang="zh"> 
这个正常情况下，改这个不是就是网站是中文语言显示了嘛，现在这个不生效

**Comment by greyli** [comment]
改哪个？

**Comment by greyli** [comment]
lang 属性只是用来声明页面上内容的语言，不会改变内容。以后这类问题请发到[交流群](http://helloflask.com#discuss)。
