### ISSUE TITLE
关于 /admin/post/manage delete post出现page not found问题

### ISSUE THREAD

**Issue by nuddles0** [greyli/bluelog#18]
当 在/admin/post/manage URL中最后一页删除最后一个条目时会出现PAGE NOT FOUND。
修改如下 ：
@admin_bp.route('/post/manage')
@login_required
def manage_post():
    page = request.args.get('page', 1, type=int)
    pages = Post.query.paginate(page=1, per_page=current_app.config['BLUELOG_MANAGE_POST_PER_PAGE']).pages
    if page > pages:
        page = pages
        return redirect(url_for('.manage_post', page=page))
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=current_app.config['BLUELOG_MANAGE_POST_PER_PAGE'])
    posts = pagination.items
    return render_template('admin/manage_post.html', page=page, pagination=pagination, posts=posts)

**Comment by greyli** [comment]
感谢反馈，已在 https://github.com/greyli/new-bluelog/pull/15 修复。
