### ISSUE TITLE
删除文章时，没有删除与文章一同上传的图片

### ISSUE THREAD

**Issue by WalnutPKU** [greyli/bluelog#19]
在本地测试环境下上传带图文本后保存，再删除post，发现一同上传的图片没有被删除，不知道在哪里能找到或生成这些图片的索引呢?

**Comment by greyli** [comment]
图片上传的功能是后加的，只是作为一个简单的示例，所以不是很完善。

你可以在上传图片的时候为图片创建数据库记录，保存文件路径，关联到对应的文章。文章删除的时候找到关联的图片并删掉。可以参考第九章的实现写一个数据库监听函数。

**Comment by mutalisk999** [comment]
个人感觉不删是ok的，如果两篇帖子都依赖同一个图片，图片上传了多次，但是其实真实保存下来的图片文件就同一个，如果删除了，另一个post的显示就会出问题。

不删或者采用类似于引用计数删除的方式

**Comment by mutalisk999** [comment]
个人感觉不删是ok的，如果两篇帖子都依赖同一个图片，图片上传了多次，但是其实真实保存下来的图片文件就同一个，如果删除了，另一个post的显示就会出问题。

不删或者采用类似于引用计数删除的方式

**Comment by greyli** [comment]
感谢反馈，已在 https://github.com/greyli/new-bluelog/pull/17 处理
