### ISSUE TITLE
admin/post/manage 页面渲染报错：'None' has no attribute 'id' 

### ISSUE THREAD

**Issue by Alex1996a** [greyli/bluelog#2]
### 背景：
按照作者书中思路和源码一步步搭建。
在测试过程中出现如下问题。
### 问题描述：
在访问路由 `admin/post/manage` 的时候报错：`jinja2.exceptions.UndefinedError: 'None' has no attribute 'id'`

### 问题代码定位：
在` templates/admin/mange_post.html`文件下： 

1、`<td><a href="{{ url_for('front.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>`
2、`<td><a href="{{ url_for('blog.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a></td>`

代码的目的是：渲染 Post 相关的 category 和 comment 
### 问题原因：
1、代码逻辑忽略了 post 有可能没有 comment 和 category 的情况。
2、手动在 shell 创建了几条 POST 的测试数据，但是这些数据没有包含 Category 和 Comment 。
3、于是在渲染的时 ,Post.category , Post.comment 为 None,从而导致模板渲染失败。

### 改进
1、在这类的代码前添加逻辑 {% if post.category } dosomething {% else %}   None{% endif %} 

2、由于上面会出现很多重复判断代码，因此可以抽取重复逻辑，用使用宏定义一个渲染函数。

### ps 

感谢作者优秀的书籍和源码，收获良多~~~~

**Comment by greyli** [comment]
感谢反馈！

我测试了一下，当通过**程序页面**添加一篇文章时，默认文章分类会被设为“Default”，所以管理页面不会出错；而评论会正确显示为0。

PS：谢谢你的认可，欢迎来[豆瓣页面](https://book.douban.com/subject/30310340/)写短评。

**Comment by Alex1996a** [comment]
> 感谢反馈！
> 
> 我测试了一下，当通过**程序页面**添加一篇文章时，默认文章分类会被设为“Default”，所以管理页面不会出错；而评论会正确显示为0。
> 
> PS：谢谢你的认可，欢迎来[豆瓣页面](https://book.douban.com/subject/30310340/)写短评。

好的，谢谢指正，可能是我代码实现出现了疏漏。
辛苦~~~

**Comment by greyli** [comment]
没事，你在创建文章记录的时候记得设置分类就可以了。
