### ISSUE TITLE
ck_editor's bug. 管理员登陆后setting里面的about栏的ck_editor没有上传图片的功能。

### ISSUE THREAD

**Issue by crissallan** [greyli/bluelog#32]
管理员登陆后setting里面的about栏的ck_editor没有上传图片的功能。但是新建post的时候，编辑body就有上传图片的功能。

**Comment by greyli** [comment]
需要在 about.html 中 scripts 块最后添加下面的代码让 CKEditor 配置生效：

```html
{{ ckeditor.config(name='about') }}
```
