### ISSUE TITLE
如何在about页面，添加一个头像框放置自己的照片

### ISSUE THREAD

**Issue by crissallan** [greyli/bluelog#33]
如何在about页面，添加一个头像框放置自己的照片？ 需要在哪个html模板上做一些改动呢。
多谢！

**Comment by greyli** [comment]
简单的方式：
- 直接用 CKEditor 的编辑框上传图片

复杂的方式：
- 对应模型类加一个图片文件名字段
- 在对应表单类里加一个文件上传字段
- 在对应模板里对应位置渲染图片的 `<img>` 元素

**Comment by crissallan** [comment]
> * 应表单类里加一个文件上传字段

好的！非常感谢
！
