### ISSUE TITLE
如果想让文章编辑支持markdown语法，该如何做呢？

### ISSUE THREAD

**Issue by crissallan** [greyli/bluelog#34]
您好，
如果我想放弃CKEditor（因为它不支持数学公式）而想使用支持markdown语法的编辑器，该如何做呢？（比如修改哪些模型和模板之类的）

另外，目前看到的开源的后端渲染的就是Editormd，不知道您是否有其它推荐的？

多谢！

**Comment by greyli** [comment]
有一个集成 Pagedown 的 [Flask-Pagedown](https://github.com/miguelgrinberg/Flask-PageDown) 扩展，其他开源实现不熟悉。也可以考虑参考 [CatChat](https://github.com/greyli/catchat) 手动实现。

后续有问题请发到 [HelloFlask Discuss](https://discuss.helloflask.com/).
