### ISSUE TITLE
[问题] 如何显示Post的 shortcut ?

### ISSUE THREAD

**Issue by kurt-steiner** [greyli/bluelog#42]
![image](https://user-images.githubusercontent.com/46296608/190912547-74bf1bb9-e714-4baa-b1be-b5ebd54bb0e6.png)
如图，Post 入口中显示的是 Post 内容的简短部分，而且没有html标签在里面，我想问问这是怎么做到的，难道原来的 Post 内容里没有html内容吗?

**Comment by Mz1z** [comment]
这个使用了template文件夹中的模板，是用jinja2的修饰器做的

**Comment by greyli** [comment]
https://github.com/greyli/bluelog/blob/master/bluelog/templates/blog/_posts.html#L5

用了 striptags 过滤器
