### ISSUE TITLE
_init__.py在注册蓝图的时候默认是访问哪个路径

### ISSUE THREAD

**Issue by mylysddp** [greyli/bluelog#5]
在__init__.py中是这样导入蓝图的
from bluelog.blueprints.auth import auth_bp
一般情况下蓝图有没有默认访问路径，可以通过哪个参数来修改这个访问路径么

**Comment by greyli** [comment]
没太明白你的意思，举个例子？

**Comment by meizhaohui** [comment]
没有默认的路径，可以通过 `app.register_blueprint(auth_bp, url_prefix='/auth')` 的形式指定auth_bp蓝图使用/auth前缀.
