### ISSUE TITLE
manage_category()的参数？

### ISSUE THREAD

**Issue by Ecvelnter** [greyli/bluelog#7]
bluelog/bluelog/blueprints/admin.py
manage_category()
这个函数没定义参数呢？

**Comment by greyli** [comment]
什么参数？

**Comment by greyli** [comment]
分类数据，也就是模板里使用的 `categories` 变量使用模板上下文处理函数注入到模板里了（[相关代码](https://github.com/greyli/bluelog/blob/master/bluelog/__init__.py#L108)），所以这里不需要重复传递。

**Comment by Ecvelnter** [comment]
哇！谢谢！

**Comment by greyli** [comment]
不客气。
