### ISSUE TITLE
Chrome 和 Safari 显示有区别

### ISSUE THREAD

**Issue by DapangLiu** [greyli/bluelog#8]
<img width="1911" alt="chrome" src="https://user-images.githubusercontent.com/21965264/52450489-35462400-2b09-11e9-9694-b1cfcf60f6d7.png">

Above is Chrome version.

<img width="1920" alt="safari" src="https://user-images.githubusercontent.com/21965264/52450493-38411480-2b09-11e9-9cb1-1551a03580de.png">

Above is Safari version.

可能是对不同浏览器适配不太一样？Chrome 显示的比较小？按钮都挤在一起了。看起来像是宽度不够。

**Comment by greyli** [comment]
每一章开始有提到，因为每个项目的 css 文件名都是 style.css，所以运行新项目时需要清除缓存。Mac 下可以尝试使用 ctrl+shift+r，或是在设置里清除。

**Comment by DapangLiu** [comment]
感谢！

**Comment by greyli** [comment]
:)
